add a check for ssl so that there are less errors from users

diff --git a/spring-back-end/bin/startup-scripts/run b/spring-back-end/bin/startup-scripts/run
--- a/spring-back-end/bin/startup-scripts/run
+++ b/spring-back-end/bin/startup-scripts/run
@@ -51,4 +51,37 @@ while getopts "hp:" opt; do
   esac
 done
 
+SSL_FILE_TYPE=".p12z"
+
+echo
+echo "Checking to make sure there is an SSL p12 file in the repo."
+echo
+
+if [[ $(ls -A "${SSL_KEYSTORE_DIR}"/*"${SSL_FILE_TYPE}"*) ]]; then
+  echo "There is a ${SSL_FILE_TYPE} file, proceeding."
+  echo
+else
+  echo
+  echo -e "We didn't find a ${SSL_FILE_TYPE} in ${SSL_KEYSTORE_DIR}. Without this file, SSL will not be enabled; and when you try and run the app, you'll get an error indicating the server.ssl.key-store file referenced in the application-local.properties could not be found." | fmt
+  echo
+  echo -e "To generate this file, run the 'enable-localhost-https' script in ${SCRIPT_DIR}/../ssl"
+  echo
+  read -r -p "Do you want to try and run the jar anyway? (y/n) " yn
+  case $yn in
+  y | Y)
+    echo "OK. Continuing..."
+    ;;
+  n | N)
+    echo "OK. Quitting here..."
+    exit 0
+    ;;
+  *)
+    echo "invalid response"
+    exit 1
+    ;;
+  esac
+fi
+
+exit
+
 java -Dspring.profiles.active="${PROFILE}" -jar "${SCRIPT_DIR}"/../../pjl-application/pjl-application-core/target/pjl-application-core.jar
